split: true

key-clusters:
  main:
    position:
      anchor: origin
      offset: [0, 0, 16]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    aliases:
      top-left: [1, first]
      top-right: [last, first]

by-key:
  parameters:
    wall:
      north:
        parallel: 2
      east:
        parallel: 2
      south:
        parallel: 2
      west:
        parallel: 2

mcu:
  include: true
  position:
    corner: SSW
    prefer-rear-housing: true
    anchor: top-right
    rotation: [0, -1.570796, 0]
    offset: [0, 0, -6]

connection:
  include: true
  socket-size: [6.1, 4, 5]
  position:
    corner: SSW
    prefer-rear-housing: true
    anchor: top-left
    offset: [0, -1, 3]
