split: true

keys:
  styles:
    default:
      style: maquette
      switch-type: mx
      skirt-length: 4.6
      top-size: [12.7, 12.7, 3.3]

key-clusters:
  main:
    position:
      anchor: origin
      offset: [0, 0, 16]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 2
    aliases:
      mcu: [1, first]
      top-left: [first, first]
      top-right: [last, first]
      bottom-left: [first, last]
      bottom-right: [last, last]

by-key:
  parameters:
    wall:
      north:
        parallel: 2
      east:
        parallel: 2
      south:
        parallel: 2
      west:
        parallel: 2

mcu:
  include: true
  position:
    corner: SSW
    prefer-rear-housing: true
    anchor: mcu
    rotation: [0, -1.570796, 0]
    offset: [0, 0, -6]

connection:
  include: true
  socket-size: [6.1, 4, 5]
  position:
    corner: SSW
    prefer-rear-housing: true
    anchor: top-right
    offset: [0, -1, 3]


case:
  bottom-plate:
    include: true
    thickness: 0.8
    installation:
      thickness: 2.5
      fasteners:
        diameter: 4
        length: 8.5
        positions:
          - anchor: top-left
            corner: SSW
            offset: [3, 3]
          - anchor: top-right
            corner: SSE
            offset: [-3, 3]
          - anchor: bottom-left
            corner: NNW
            offset: [3, -3]
          - anchor: bottom-right
            corner: NNE
            offset: [-3, -3]
