# A configuration fragment for Tom Short’s Dactyl-ManuForm, ca. v0.4.

# The long-term goal with this file is to have it produce Short’s design
# through the DMOTE application for upstream compatibility.

# As of DMOTE v0.4.0, that is not yet possible, because:
# - No internal shelf for the MCU.
# - No USB A.
# - No wire hooks.

# This is nowhere near complete even for the DMOTE v0.4.0 feature set.

case:
  bottom-plate:
    include: true
    installation:
      style: inserts
      inserts:
        diameter:
          top: 5.1
          bottom: 5.31
        length: 3.8
