# Bundled default model build parameters for a DMOTE.
# This is not the full set of available parameters.
# Read the project documentation.

keycaps:
  body-height: 7.3  # DSA-profile caps.
  resting-clearance: 6.5  # DSA on Matias switches.
switches:
  travel: 3.5
key-clusters:
  finger:
    vertical-offset: 7
    tenting: 0.27
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 3
    - rows-above-home: 1
      rows-below-home: 2
    - rows-below-home: 2
    - rows-below-home: 2
by-key:
  parameters:
    channel:
      height: 20
      top-width: 10
      margin: 0.5
  clusters:
    finger:
      columns:
        "1":
          rows:
            first:
              parameters:
                channel:
                  top-width: 15
wrist-rest:
  include: false
  style: threaded
  preview: false
  position:
    finger-key-column: 4
    key-corner: SSE
    offset: [0, -40]
  plinth-base-size: [35, 62, 44]
  lip-height: 2
  rubber:
    height:
      above-lip: 10
      below-lip: 6
    shape:
      grid-size: [4, 62]
foot-plates:
  include: true
  height: 4
  polygons:
  - points:
    - key-coordinates: [last, last]
      key-corner: WNW
      offset: [7, 0]
    - key-coordinates: [last, last]
      key-corner: NNE
    - key-coordinates: [last, -1]
      key-corner: ENE
  - points:
    - key-coordinates: [last, first]
      key-corner: SSW
      offset: [4, 1]
    - key-coordinates: [last, first]
      key-corner: NNE
      offset: [1, -5]
    - key-coordinates: [last, first]
      key-corner: ESE
  - points:
    - key-coordinates: [2, -3]
      key-corner: NNW
    - key-coordinates: [2, -3]
      key-corner: NNE
    - key-coordinates: [3, -2]
      key-corner: SSW
      offset: [0, 2]
    - key-coordinates: [2, -2]
      key-corner: SSE
      offset: [-3, -5]
