# Bundled default model build parameters for a DMOTE.
# This is not the full set of available parameters.
# Read the project documentation.

keys:
  styles:
    maquette-dsa:  # A non-printable preview of a DSA profile key.
      style: maquette
    minimal:  # A printable minimal key.
      style: minimal
key-clusters:
  main:
    position:
      anchor: origin
      offset: [0, 0, 17]
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 3
    - rows-above-home: 1
      rows-below-home: 2
    - rows-below-home: 2
    - rows-below-home: 2
    aliases:
      m0: [0, first]
      m1: [1, first]
      m2: [2, first]
      m3: [3, first]
      back: [1, last]
      far-right: [last, last]
      near-right: [last, first]
  thumb:
    position:
      anchor: m1
      offset: [-8, -20, 06]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
    aliases:
      tc: [1, 0]
      t0: [0, last]
      t1: [1, last]
      t2: [last, last]
      t3: [last, first]
      t4: [1, first]
      t5: [0, first]
  aux0:
    position:
      anchor: t5
      offset: [13, -17, 2]
    matrix-columns:
    - rows-above-home: 0
    aliases:
      a0: [0, 0]
by-key:
  parameters:
    key-style: maquette-dsa
    channel:
      height: 20
      top-width: 10
      margin: 0.5
    wall:
      thickness: 1
      bevel: 1
      north:
        perpendicular: -8
      east:
        perpendicular: -8
      south:
        perpendicular: -8
      west:
        perpendicular: -8
  clusters:
    main:
      parameters:
        layout:
          matrix:
            neutral:
              column: 2
            separation:
              row: 0
              column: 0
          pitch:
            base: 0.5
            progressive: 0.3
            intrinsic: -0.1
          roll:
            base: 0.2
            progressive: 0.06
          yaw:
            base: 0.03
      columns:
        "0":
          parameters:
            key-style: minimal
            layout:
              matrix:
                separation:
                  row: 1.8
              translation:
                early: [-4, -4, 5]
              roll:
                intrinsic: 0.3
            wall:
              north:
                extent: 0
              south:
                extent: 0
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic:
                      -0.2
                  yaw:
                    intrinsic:
                      -0.15
                  translation:
                    mid: [0, -1, 4]
        "1":
          parameters:
            wall:
              north:
                extent: 0
              south:
                extent: 0
              west:
                extent: 0
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: -0.05
                  translation:
                    early: [-1, -4, 8]
                channel:
                  top-width: 15
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, 0, 2]
        "2":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                progressive: 0.28
              translation:
                mid: [0, 3, -1]
            wall:
              east:
                extent: 1
                perpendicular: -12
              south:
                extent: 1
                perpendicular: -12
              west:
                extent: 0
          rows:
            "-3":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.8
                  translation:
                    early: [0, -16, 8]
                wall:
                  east:
                    extent: 4
            "-2":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.3
                  translation:
                    early: [0, -3.5, 2]
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, -0.5, 0]
            last:
              parameters:
                wall:
                  north:
                    extent: 0
        "3":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                base: 0.4
                progressive: 0.29
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: 0.05
                  translation:
                    early: [0.7, -4, 5]
            last:
              parameters:
                wall:
                  north:
                    extent: 0
        "4":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                progressive:
                  0.45
              yaw:
                base: 0.08
              translation:
                mid: [-0.6, -3, 5.5]
        "5":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              pitch:
                progressive:
                  0.45
              yaw:
                base: 0.1
              translation:
                mid: [-0.6, -4, 5.5]
    thumb:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 0
          roll:
            base: -1.3
            progressive: 0.45
          pitch:
            base: -0.2
            progressive: 0.25
          yaw:
            base: 1
        wall:
          north:
            extent: 1
          east:
            extent: 4
          south:
            extent: 0
          west:
            extent: 0
      columns:
        "0":
          parameters:
            layout:
              translation:
                mid: [0, -7, 0]
          rows:
            "0":
              parameters:
                layout:
                  translation:
                    early: [0.5, -2, -1]
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: -0.05
            "1":
              parameters:
                layout:
                  translation:
                    early: [-1, 1, 0]
                  yaw:
                    intrinsic: 0.1
                wall:
                  north:
                    extent: 0
        "1":
          parameters:
            layout:
              pitch:
                progressive: 0.37
              translation:
                mid: [0, 3, 0]
            wall:
              north:
                extent: 4
                perpendicular: -4
          rows:
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, -1.5, -2]
                  pitch:
                    intrinsic: -0.3
                wall:
                  east:
                    extent: 0
                    perpendicular: -14
                  south:
                    extent: 1
                    perpendicular: -14
            "1":
              parameters:
                layout:
                  translation:
                    early: [0, 0, 5]
        "2":
          parameters:
            layout:
              translation:
                mid: [0, -7, 0]
          rows:
            "0":
              parameters:
                layout:
                  translation:
                    early: [-0.5, -1.5, -1]
                  pitch:
                    intrinsic: -0.3
                  yaw:
                    intrinsic: 0.05
            "1":
              parameters:
                layout:
                  translation:
                    early: [1, 1, 0]
                  yaw:
                    intrinsic: -0.1
    aux0:
      parameters:
        layout:
          roll:
            base: 0
          pitch:
            base: 1.55
          yaw:
            base: 0
        wall:
          north:
            extent: 0
          east:
            extent: 0
          south:
            extent: 0
          west:
            extent: 0
secondaries:
  - alias: mt-0a  # Main-to-thumb cluster bridge point 0a.
    anchor: m0
    corner: SSW
    segment: 0
    offset: [0, -3, 5]
  - alias: mt-0b
    anchor: m0
    corner: SSE
    segment: 0
    offset: [0, -7, 10]
case:
  key-mount-thickness: 2.5
  web-thickness: 2.5
  rear-housing:
    include: true
    position:
      offsets:
        north: 15
        east: -1.5
        south: 3
        west: 2
    height: 53.5
    fasteners:
      diameter: 6
      bosses: true
      west:
        include: true
        offset: 0
      east:
        include: true
        offset: -13
  back-plate:
    include: false
    beam-height: 20
    fasteners:
      diameter: 6
      distance: 30
    position:
      anchor: back
      offset: [0, 0, 0]
  bottom-plate:
    include: true
    thickness: 0.8
    installation:
      fasteners:
        diameter: 3
        length: 6.5
        positions:
        - anchor: rear-housing
          corner: NNW
          offset: [2, -3]
        - anchor: rear-housing
          corner: NNE
          offset: [-2, -12]
        - anchor: far-right
          corner: ENE
          offset: [-3, -2]
        - anchor: near-right
          corner: ESE
          offset: [-3, 2]
        - anchor: a0
          corner: WSW
          offset: [-1, 0]
        - anchor: t1
          corner: NNW
          offset: [2, -4]
  leds:
    include: true
    amount: 3
    # Settings here are for WS2818 diodes at 17 mm intervals.
    housing-size: 5.5  # Real size: 5 mm.
    emitter-diameter: 4
    interval: 16.8
  tweaks:
  # First, a bunch of extra webbing at the four corners of the thumb cluster:
  - hull-around:
    - [t0, NNW, 0]
    - [t0, NNE, 0]
    - [t1, NNW, 0]
  - hull-around:
    - [t2, NNW, 0, 1]
    - [t2, NNE, 0, 1]
    - [t1, NNE, 0, 1]
  - hull-around:
    - [tc, SSE, 0]
    - [t3, WSW, 0]
    - [t4, ENE, 0]
  - chunk-size: 3
    hull-around:
    - [t4, ENE, 0]
    - [t4, SSE, 0]
    - [t3, WSW, 0]
    - hull-around:
      - [t3, SSE, 0, 1]
      - [t3, ESE, 0, 1]
  - hull-around:
    - hull-around:
      - [t3, SSE, 1, 4]
      - [t3, ESE, 1, 4]
    - hull-around:
      - [t4, ESE, 1, 4]
      - [t4, SSE, 0, 4]
  # Plating over the cluster gap:
  - chunk-size: 2
    hull-around:
    - [t1, NNE, 0, 4]
    - [t2, NNE, 0, 4]
    - [t2, ENE, 0, 4]
  # Cluster gap, west side:
  - chunk-size: 3
    hull-around:
    - [t1, NNW, 3, 4]
    - [m0, WSW, 2, 3]
    - [t1, NNE, 3, 4]
    - [m0, WSW, 0, 1]
    - [mt-0a]
    - [t1, NNE, 3, 4]
    - [t2, NNE, 3, 4]
  # Cluster gap between m0 and t2:
  - chunk-size: 3
    hull-around:
    - [m0, SSW]
    - [m0, SSE]
    - [mt-0a]
    - [mt-0b]
    - hull-around:
      - [t2, NNE, 3, 4]
      - [t2, ENE, 3, 4]
    - [t2, ESE, 4]
  # More cluster gap:
  - chunk-size: 3
    hull-around:
    - [m0, SSE]
    - [mt-0b]
    - [m1, WSW]
    - [t2, ESE, 4]
  # Webbing between m0 and m1:
  - hull-around:
    - [m0, SSE]
    - [m1, WNW]
    - [m1, WSW]
  # The middle topside plate:
  - chunk-size: 3
    hull-around:
    - [m1, SSW]
    - [t2, ESE, 4]
    - [m1, SSE]
    - [m2, WSW]
    - [t2, ESE, 4]
    - [t3, ENE, 4]
  # The west side of m2:
  - hull-around:
    - [m1, SSE]
    - [m2, WNW, 0]
    - [m2, WSW, 0]
  # The eastern topside plate:
  - chunk-size: 3
    hull-around:
    - [m2, WSW, 0, 1]
    - [t3, NNE, 4]
    - [m2, SSW, 0, 1]
    - hull-around:
      - [t3, ESE, 4]
      - [t3, SSE, 4]
    - hull-around:
      - [m2, ESE, 3, 4]
      - [m2, SSE, 3, 4]
    - [t4, ESE, 4]
    - [m2, ESE, 3, 4]
  # The low eastern plate:
  - chunk-size: 3
    hull-around:
    - [t4, SSE, 0, 1]
    - [t4, SSW, 0, 1]
    - [t4, SSE, 3, 4]
    - hull-around:
      - [a0, NNE, 0, 1]
      - [a0, ENE, 0, 1]
    - hull-around:
      - [m2, ESE, 3, 4]
      - [m2, SSE, 3, 4]
    - [m2, ENE, 3, 4]
    - [a0, ENE, 0, 1]
    - [a0, ESE, 0, 1]
  # A triangular southern wall of m2:
  - hull-around:
    - [m2, SSW, 0, 1]
    - [m2, SSE, 0, 3]
    - [m2, ESE, 0, 3]
  # Webbing at the lower near corner of the thumb cluster:
  - chunk-size: 3
    hull-around:
    - [t4, WNW, 0]
    - [t4, WSW, 0]
    - [t5, SSE, 0]
    - [a0, NNW, 0]
    - [t5, SSW, 0]
  # Webbing between the thumb and aux0 clusters:
  - hull-around:
    - [t4, SSW, 0, 1]
    - [a0, WNW, 0]
    - [a0, ENE, 0]
  # A plate to ground beneath the entire thumb cluster:
  - to-ground: true
    chunk-size: 2
    hull-around:
    - [m0, WSW, 2, 3]
    - [t1, NNW, 2, 3]
    - [t1, NNW, 0, 1]
    - [t0, WNW, 0, 1]
    - [t0, WSW, 0, 1]
    - [t5, WNW, 0, 1]
    - [t5, WSW, 0, 1]
    - [t5, SSW, 0, 1]
    - hull-around:
      - [a0, WNW, 0]
      - [a0, WSW, 0]
    - [a0, SSW, 0]
    - [a0, ESE, 0, 1]
    - [m2, ENE, 3, 4]
    - [m2, NNE, 3, 4]
    - [m3, WSW, 3, 4]
    - [m3, SSW, 3, 4]
mcu:
  type: promicro
  margin: 0.25
  position:
    prefer-rear-housing: true
    anchor: back
    corner: ENE
    offset: [-1, 0, 2]
  support:
    style: lock
    height-factor: 0.5
    lateral-spacing: 2.5
    lock:
      fastener:
        diameter: 3
      socket:
        thickness: 1.5
      bolt:
        clearance: 2.5
        overshoot: 1
        mount-length: 10
        mount-thickness: 6
    stop:
      anchor: back
      direction: east
      gripper:
        notch-depth: 0.4
        total-depth: 5
        grip-width: 0.6
connection:
  socket-size: [10, 11, 17.7]  # 616E minus the vertical bar is 10 mm wide.
  position:
    prefer-rear-housing: true
    anchor: back
    corner: ENE
    raise: true
wrist-rest:
  include: false
  position:
    offset: [83, -90]
  plinth-height: 2
  shape:
    spline:
      main-points:
      - position: [0, 22]
        alias: plinth-left
      - position: [20, 30]
      - position: [35, 28]
      - position: [41, 50]
      - position: [50, 63]
      - position: [68, 62]
        alias: plinth-right
      - position: [74, 42]
      - position: [63, 20]
      - position: [50, 5]
      - position: [30, 0]
        alias: plinth-near
      - position: [3, 2]
      resolution: 2
    lip:
      inset: -0.6
      height: 1.5
    pad:
      height:
        surface-range: 5
        lip-to-surface: 3
        below-lip: 2
      surface:
        edge:
          inset: 8
          resolution: 5
  rotation:
    pitch: 0.05
    roll: 0.05
  sprues:
    include: true
    inset: 10
    diameter: 12
    positions:
    - anchor: plinth-left
      offset: [17, -3]
    - anchor: plinth-right
      offset: [-8, -16]
  bottom-plate:
    include: true
    inset: 2
    fastener-positions:
    - anchor: plinth-left
    - anchor: plinth-near
      offset: [0, 4]
    - anchor: plinth-right
dfm:
  error-general: -0.5
