# Bundled default model build parameters for a DMOTE.
# This is not the full set of available parameters.
# Read the project documentation.

keycaps:
  body-height: 7.3  # DSA-profile caps.
  resting-clearance: 6.5  # DSA on Matias switches.
switches:
  travel: 3.5
key-clusters:
  finger:
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 3
    - rows-above-home: 1
      rows-below-home: 2
    - rows-below-home: 2
    - rows-below-home: 2
    aliases:
      f0: [0, first]
      f1: [1, first]
      f2: [2, first]
  thumb:
    position:
      key-alias: f1
      offset: [-15, -20, 2]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
    aliases:
      t0: [0, last]
      t1: [1, last]
      t2: [last, last]
      t3: [last, first]
      t4: [1, first]
      t5: [0, first]
by-key:
  parameters:
    channel:
      height: 20
      top-width: 10
      margin: 0.5
    wall:
      thickness: 1
      bevel: 1
      north:
        perpendicular: -8
      east:
        perpendicular: -8
      south:
        perpendicular: -8
      west:
        perpendicular: -8
  clusters:
    finger:
      parameters:
        layout:
          matrix:
            neutral:
              column: 2
            separation:
              row: -0.4
              column: 0.3
          pitch:
            base: 0.26
            progressive: 0.45
          roll:
            base: 0.26
            progressive: 0.06
          translation:
            late: [0, 0, 7]
      columns:
        "0":
          parameters:
            wall:
              south:
                extent: 3
                perpendicular: 8
        "1":
          parameters:
            wall:
              south:
                extent: 3
                parallel: 3
                perpendicular: 8
              west:
                extent: 3
                parallel: 3
                perpendicular: 8
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  translation:
                    early: [-1, -2, 3]
                channel:
                  top-width: 15
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]

        "2":
          parameters:
            layout:
              translation:
                mid: [0, 3, -4]
            wall:
              south:
                extent: 0
              west:
                extent: 0
          rows:
            "-3":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.2
                  translation:
                    early: [0, -5, 4]
            "-2":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  translation:
                    early: [0, -2, 3]
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
        "3":
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  translation:
                    early: [1, -2, 3]
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
        "4":
          parameters:
            layout:
              matrix:
                neutral:
                  row: -1
              translation:
                mid: [0, 4, 5]
          rows:
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
        "5":
          parameters:
            layout:
              matrix:
                neutral:
                  row: -1
              translation:
                mid: [0, 4, 5]
    thumb:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 0.5
          roll:
            base: -1.1
            progressive: 0.3
          pitch:
            base: -0.4
            progressive: 0.3
          yaw:
            base: 1
        wall:
          north:
            extent: 0
          east:
            extent: 4
          south:
            extent: 4
          west:
            extent: 0
      columns:
        "0":
          parameters:
            layout:
              translation:
                mid: [0, -4, 0]
          rows:
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, -2, 0]
                  pitch:
                    intrinsic: -0.25
        "1":
          parameters:
            layout:
              translation:
                mid: [0, 3, 0]
          rows:
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, 1, -4]
            "1":
              parameters:
                layout:
                  translation:
                    early: [0, 0, 4]
        "2":
          parameters:
            layout:
              translation:
                mid: [0, -4, 0]
          rows:
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, -2, 0]
                  pitch:
                    intrinsic: -0.25
wrist-rest:
  include: false
  style: threaded
  position:
    finger-key-column: 4
    key-corner: SSE
    offset: [0, -40]
  plinth-base-size: [35, 62, 44]
  lip-height: 2
  rubber:
    height:
      above-lip: 10
      below-lip: 6
    shape:
      grid-size: [4, 62]
foot-plates:
  include: true
  height: 4
  polygons:
  - points:
    - key-coordinates: [last, last]
      key-corner: WNW
      offset: [7, 0]
    - key-coordinates: [last, last]
      key-corner: NNE
    - key-coordinates: [last, -1]
      key-corner: ENE
  - points:
    - key-coordinates: [last, first]
      key-corner: SSW
      offset: [4, 1]
    - key-coordinates: [last, first]
      key-corner: NNE
      offset: [1, -5]
    - key-coordinates: [last, first]
      key-corner: ESE
  - points:
    - key-coordinates: [2, -3]
      key-corner: NNW
    - key-coordinates: [2, -3]
      key-corner: NNE
    - key-coordinates: [3, -2]
      key-corner: SSW
      offset: [0, 2]
    - key-coordinates: [2, -2]
      key-corner: SSE
      offset: [-3, -5]
