# Bundled default model build parameters for a DMOTE.
# This is not the full set of available parameters.
# Read the project documentation.

key-clusters:
  finger:
    tenting: 0.27
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 3
    - rows-above-home: 1
      rows-below-home: 2
    - rows-below-home: 2
    - rows-below-home: 2
wrist-rest:
  include: false
  style: threaded
  preview: false
  position:
    finger-key-column: 4
    key-corner: SSE
    offset: [0, -40]
  plinth-base-size: [35, 62, 44]
  lip-height: 2
  rubber:
    height:
      above-lip: 10
      below-lip: 6
    shape:
      grid-size: [4, 62]
foot-plates:
  include: true
  height: 4
  polygons:
  - points:
    - key-coordinates: [5, 0]
      key-corner: WNW
      offset: [7, 0]
    - key-coordinates: [5, 0]
      key-corner: NNE
    - key-coordinates: [5, -1]
      key-corner: ENE
  - points:
    - key-coordinates: [5, -2]
      key-corner: SSW
      offset: [4, 1]
    - key-coordinates: [5, -2]
      key-corner: NNE
      offset: [1, -5]
    - key-coordinates: [5, -2]
      key-corner: ESE
  - points:
    - key-coordinates: [2, -3]
      key-corner: NNW
    - key-coordinates: [2, -3]
      key-corner: NNE
    - key-coordinates: [3, -2]
      key-corner: SSW
      offset: [0, 2]
    - key-coordinates: [2, -2]
      key-corner: SSE
      offset: [-3, -5]
